<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <AssemblyName>VisionFlowStudio.LicenseTool</AssemblyName>
    <RootNamespace>VisionFlowStudio.LicenseTool</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\VisionFlowStudio.Licensing\VisionFlowStudio.Licensing.csproj" />
  </ItemGroup>
</Project>
